### ISSUE TITLE
Could the same packages in deep dependencies be merged?

### ISSUE THREAD

**Issue by miserylee** [megahertz/howfat#16]
many duplicated dependencies will be hoisted, only one copy should be calculated to the package size

**Comment by miserylee** [comment]
Okay, maybe I mistake review the result.
I have an idea, could the --reporter option support flatten list to show all deduplicated modules, which should be more clear to analyze.
Thanks for your quickly reply ❤

**Comment by megahertz** [comment]
Do you mean a table-like view, but where sub dependencies are also listed?
