### ISSUE TITLE
Ignore missing packages

### ISSUE THREAD

**Issue by pkit** [megahertz/howfat#3]
Sometimes packages are not on npm registry: local development, monrepos, etc.
It would be nice to get these ignored and not failing, maybe behind a flag: `--ignoreMissing`.
Although looking at the code it seems that pulling 404 all the way up to the high level can be non-trivial.

**Comment by megahertz** [comment]
I'll think on it.

**Comment by pkit** [comment]
Overall I like it a lot. It's the only tool that does what I need.
