### ISSUE TITLE
Do not hardcode default registry.npmjs.org

### ISSUE THREAD

**Issue by ghost** [megahertz/howfat#6]
When running this tool against packages hosted on private registries and mirrors, it will not work

https://github.com/megahertz/howfat/blob/00269eac85c184e2e6efffdb45c8370b34332958/src/package/fetchers/NpmFetcher.js#L27

The best way is to inherit the registry from npm configuration or allow to override it through CLI flag. That way, we will gather statistics for private packages as well.

**Comment by megahertz** [comment]
Thank you, will try to add the feature later

**Comment by zeroarst** [comment]
Just wondering if this has been updated?

**Comment by megahertz** [comment]
Implemented in v0.3.0
